"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { supabase } from "@/lib/supabase";

export default function OwnerOrdersPage(){
  const params=useParams<{id:string}>(); const businessId=Number(params.id);
  const [orders,setOrders]=useState<any[]>([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
  async function token(){const {data:{session}}=await supabase.auth.getSession(); if(!session?.access_token)throw new Error("로그인이 필요합니다."); return session.access_token}
  async function load(){try{const t=await token(); const r=await fetch(`/api/owner/business/${businessId}/orders`,{headers:{Authorization:`Bearer ${t}`},cache:"no-store"}); const j=await r.json(); if(!r.ok)throw new Error(j.error); setOrders(j.orders||[])}catch(e:any){setError(e.message)}finally{setLoading(false)}}
  useEffect(()=>{void load(); const timer=setInterval(()=>void load(),30000); return()=>clearInterval(timer)},[businessId]);
  async function status(orderId:number,next:string){const t=await token(); const r=await fetch(`/api/owner/business/${businessId}/orders/${orderId}`,{method:"PATCH",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({status:next})}); const j=await r.json(); if(!r.ok) return alert(j.error||"Failed"); await load();}
  return <main className="mx-auto max-w-5xl p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-black text-gray-400">ONLINE ORDERS</p><h1 className="text-2xl font-black">Orders</h1></div><button onClick={()=>void load()} className="rounded-xl border px-4 py-2 text-xs font-black">REFRESH</button></div>{error?<p className="mt-4 text-red-600">{error}</p>:null}{loading?<p className="mt-6">Loading…</p>:null}<div className="mt-5 space-y-4">{orders.map(o=><article key={o.id} className="rounded-2xl border p-4 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-black text-gray-400">#{o.order_number} · {String(o.fulfillment_type).toUpperCase()}</div><h2 className="text-lg font-black">{o.customer_name}</h2><p className="text-sm text-gray-600">{o.customer_phone} · {o.requested_time||"ASAP"}</p></div><div className="text-right"><div className="text-xl font-black">${Number(o.total||0).toFixed(2)}</div><div className="text-xs font-bold">{o.payment_status}</div></div></div><div className="mt-3 space-y-1">{(o.restaurant_order_items||[]).map((i:any)=><div key={i.id} className="flex justify-between text-sm"><span><b>{i.quantity}×</b> {i.item_name}</span><span>${Number(i.line_total||0).toFixed(2)}</span></div>)}</div><div className="mt-4 flex flex-wrap gap-2">{["new","preparing","ready","completed","cancelled"].map(s=><button key={s} onClick={()=>void status(o.id,s)} className={`rounded-full border px-3 py-2 text-xs font-black ${o.order_status===s?"bg-gray-950 text-white":""}`}>{s.toUpperCase()}</button>)}</div></article>)}</div></main>
}
